### ISSUE TITLE
Possible source code license issue i.e. not under Ms-PL

### ISSUE THREAD

**Issue by mysticmind** [joeaudette/cloudscribe.HtmlAgilityPak#2]
I was just taking a look at this project. The original source code in codeplex is licensed under Microsoft Public License (Ms-PL) and all derivative work source code distribution should also be licensed under Ms-PL and object code can be licensed under any compatible license (you have Apache, that is okay).

I understand you have this as a temporary one until an official one is published. But it would be better if you could update the license file to state that source code is licensed under Ms-PL and object code is licensed under Apache. Put both the licenses one after other.

No one is going to bother much and it will go unnoticed. Just wanted to keep you posted since I noticed it.

**Comment by joeaudette** [comment]
I have removed the LICENSE file from this repo since it is different than the original license, I don't want to assert any license that is different. I defaulted to Apache when I created this repo because that is what the .NET Core and ASP.NET are licensed under. I suspect that if there is ever an official update to HtmlAgilityPak for .NET Core there is a good chance that they will use a different license.
